gpu: "1"
multi_gpu: null

model_name: PointConv

full: True

arch: PointConv
last_relu: False
allow_less_points: False

pretrain: ../pretrained/model_kitti_r.pth

dim: 3
num_points: 8192
batch_size: 1

DEVICE: cuda

evaluate: True
resume: True

dataset: KITTI_R_SP
data_root: /path_to/



# miscalleneous
workers: 1








